[tools]
ruby = "latest"
go = "latest"

node = "latest"
"npm:pnpm" = "latest"

python = "latest"
"pipx:ruff" = "latest"
"pipx:ty" = "latest"
"pipx:yt-dlp" = "latest"

aws-cli = "latest"
gcloud = "latest"
e1s = "latest"

[settings]
experimental = true
ruby.compile = true
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["ruby", "python"]
